packages:
  - apps/*
  - packages/*

allowBuilds:
  '@swc/core': true
  better-sqlite3: true
  esbuild: true
  msw: true

catalog:
  "@tailwindcss/vite": ^4.3.0
  "@tanstack/match-sorter-utils": "^9.0.0-alpha.4"
  "@tanstack/react-router": "^1.169.2"
  "@tanstack/react-router-devtools": "^1.166.13"
  "@tanstack/react-table": "9.0.0-alpha.45"
  "@tanstack/react-virtual": "^3.13.24"
  "@tanstack/router-plugin": "^1.167.35"
  "@types/node": ^25.7.0
  "@types/react": ~19.2.14
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": "^6.0.1"
  "@vitejs/plugin-react-swc": "^4.3.0"
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dotenv: ^17.4.2
  "jazz-tools": 2.0.0-alpha.46
  little-timestamp: ^1.0.0
  lucide-react: ^1.14.0
  react: 19.2.6
  react-dom: 19.2.6
  swr: "^2.4.1"
  tailwind-merge: ^3.6.0
  tailwindcss: ^4.3.0
  typescript: ^6.0.3
  "vite": "^8.0.12"
  "vite-plugin-top-level-await": "^1.6.0"
  "vite-plugin-wasm": "^3.6.0"

# onlyBuiltDependencies:
