/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnRouteImport } from './routes/conn'
import { Route as ConnNewRouteImport } from './routes/conn/new'
import { Route as ConnConnectionIdIndexRouteImport } from './routes/conn/$connectionId/index'
import { Route as ConnConnectionIdBranchIndexRouteImport } from './routes/conn/$connectionId/$branch/index'
import { Route as ConnConnectionIdBranchSchemaHashIndexRouteImport } from './routes/conn/$connectionId/$branch/$schemaHash/index'
import { Route as ConnConnectionIdBranchSchemaHashTablesRouteImport } from './routes/conn/$connectionId/$branch/$schemaHash/tables'
import { Route as ConnConnectionIdBranchSchemaHashLiveQueryRouteImport } from './routes/conn/$connectionId/$branch/$schemaHash/live-query'
import { Route as ConnConnectionIdBranchSchemaHashTablesIndexRouteImport } from './routes/conn/$connectionId/$branch/$schemaHash/tables/index'
import { Route as ConnConnectionIdBranchSchemaHashLiveQueryIndexRouteImport } from './routes/conn/$connectionId/$branch/$schemaHash/live-query/index'
import { Route as ConnConnectionIdBranchSchemaHashTablesTableNameIndexRouteImport } from './routes/conn/$connectionId/$branch/$schemaHash/tables/$tableName/index'

const ConnRoute = ConnRouteImport.update({
  id: '/conn',
  path: '/conn',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnNewRoute = ConnNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ConnRoute,
} as any)
const ConnConnectionIdIndexRoute = ConnConnectionIdIndexRouteImport.update({
  id: '/$connectionId/',
  path: '/$connectionId/',
  getParentRoute: () => ConnRoute,
} as any)
const ConnConnectionIdBranchIndexRoute =
  ConnConnectionIdBranchIndexRouteImport.update({
    id: '/$connectionId/$branch/',
    path: '/$connectionId/$branch/',
    getParentRoute: () => ConnRoute,
  } as any)
const ConnConnectionIdBranchSchemaHashIndexRoute =
  ConnConnectionIdBranchSchemaHashIndexRouteImport.update({
    id: '/$connectionId/$branch/$schemaHash/',
    path: '/$connectionId/$branch/$schemaHash/',
    getParentRoute: () => ConnRoute,
  } as any)
const ConnConnectionIdBranchSchemaHashTablesRoute =
  ConnConnectionIdBranchSchemaHashTablesRouteImport.update({
    id: '/$connectionId/$branch/$schemaHash/tables',
    path: '/$connectionId/$branch/$schemaHash/tables',
    getParentRoute: () => ConnRoute,
  } as any)
const ConnConnectionIdBranchSchemaHashLiveQueryRoute =
  ConnConnectionIdBranchSchemaHashLiveQueryRouteImport.update({
    id: '/$connectionId/$branch/$schemaHash/live-query',
    path: '/$connectionId/$branch/$schemaHash/live-query',
    getParentRoute: () => ConnRoute,
  } as any)
const ConnConnectionIdBranchSchemaHashTablesIndexRoute =
  ConnConnectionIdBranchSchemaHashTablesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnConnectionIdBranchSchemaHashTablesRoute,
  } as any)
const ConnConnectionIdBranchSchemaHashLiveQueryIndexRoute =
  ConnConnectionIdBranchSchemaHashLiveQueryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnConnectionIdBranchSchemaHashLiveQueryRoute,
  } as any)
const ConnConnectionIdBranchSchemaHashTablesTableNameIndexRoute =
  ConnConnectionIdBranchSchemaHashTablesTableNameIndexRouteImport.update({
    id: '/$tableName/',
    path: '/$tableName/',
    getParentRoute: () => ConnConnectionIdBranchSchemaHashTablesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/conn': typeof ConnRouteWithChildren
  '/conn/new': typeof ConnNewRoute
  '/conn/$connectionId/': typeof ConnConnectionIdIndexRoute
  '/conn/$connectionId/$branch/': typeof ConnConnectionIdBranchIndexRoute
  '/conn/$connectionId/$branch/$schemaHash/live-query': typeof ConnConnectionIdBranchSchemaHashLiveQueryRouteWithChildren
  '/conn/$connectionId/$branch/$schemaHash/tables': typeof ConnConnectionIdBranchSchemaHashTablesRouteWithChildren
  '/conn/$connectionId/$branch/$schemaHash/': typeof ConnConnectionIdBranchSchemaHashIndexRoute
  '/conn/$connectionId/$branch/$schemaHash/live-query/': typeof ConnConnectionIdBranchSchemaHashLiveQueryIndexRoute
  '/conn/$connectionId/$branch/$schemaHash/tables/': typeof ConnConnectionIdBranchSchemaHashTablesIndexRoute
  '/conn/$connectionId/$branch/$schemaHash/tables/$tableName/': typeof ConnConnectionIdBranchSchemaHashTablesTableNameIndexRoute
}
export interface FileRoutesByTo {
  '/conn': typeof ConnRouteWithChildren
  '/conn/new': typeof ConnNewRoute
  '/conn/$connectionId': typeof ConnConnectionIdIndexRoute
  '/conn/$connectionId/$branch': typeof ConnConnectionIdBranchIndexRoute
  '/conn/$connectionId/$branch/$schemaHash': typeof ConnConnectionIdBranchSchemaHashIndexRoute
  '/conn/$connectionId/$branch/$schemaHash/live-query': typeof ConnConnectionIdBranchSchemaHashLiveQueryIndexRoute
  '/conn/$connectionId/$branch/$schemaHash/tables': typeof ConnConnectionIdBranchSchemaHashTablesIndexRoute
  '/conn/$connectionId/$branch/$schemaHash/tables/$tableName': typeof ConnConnectionIdBranchSchemaHashTablesTableNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/conn': typeof ConnRouteWithChildren
  '/conn/new': typeof ConnNewRoute
  '/conn/$connectionId/': typeof ConnConnectionIdIndexRoute
  '/conn/$connectionId/$branch/': typeof ConnConnectionIdBranchIndexRoute
  '/conn/$connectionId/$branch/$schemaHash/live-query': typeof ConnConnectionIdBranchSchemaHashLiveQueryRouteWithChildren
  '/conn/$connectionId/$branch/$schemaHash/tables': typeof ConnConnectionIdBranchSchemaHashTablesRouteWithChildren
  '/conn/$connectionId/$branch/$schemaHash/': typeof ConnConnectionIdBranchSchemaHashIndexRoute
  '/conn/$connectionId/$branch/$schemaHash/live-query/': typeof ConnConnectionIdBranchSchemaHashLiveQueryIndexRoute
  '/conn/$connectionId/$branch/$schemaHash/tables/': typeof ConnConnectionIdBranchSchemaHashTablesIndexRoute
  '/conn/$connectionId/$branch/$schemaHash/tables/$tableName/': typeof ConnConnectionIdBranchSchemaHashTablesTableNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/conn'
    | '/conn/new'
    | '/conn/$connectionId/'
    | '/conn/$connectionId/$branch/'
    | '/conn/$connectionId/$branch/$schemaHash/live-query'
    | '/conn/$connectionId/$branch/$schemaHash/tables'
    | '/conn/$connectionId/$branch/$schemaHash/'
    | '/conn/$connectionId/$branch/$schemaHash/live-query/'
    | '/conn/$connectionId/$branch/$schemaHash/tables/'
    | '/conn/$connectionId/$branch/$schemaHash/tables/$tableName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/conn'
    | '/conn/new'
    | '/conn/$connectionId'
    | '/conn/$connectionId/$branch'
    | '/conn/$connectionId/$branch/$schemaHash'
    | '/conn/$connectionId/$branch/$schemaHash/live-query'
    | '/conn/$connectionId/$branch/$schemaHash/tables'
    | '/conn/$connectionId/$branch/$schemaHash/tables/$tableName'
  id:
    | '__root__'
    | '/conn'
    | '/conn/new'
    | '/conn/$connectionId/'
    | '/conn/$connectionId/$branch/'
    | '/conn/$connectionId/$branch/$schemaHash/live-query'
    | '/conn/$connectionId/$branch/$schemaHash/tables'
    | '/conn/$connectionId/$branch/$schemaHash/'
    | '/conn/$connectionId/$branch/$schemaHash/live-query/'
    | '/conn/$connectionId/$branch/$schemaHash/tables/'
    | '/conn/$connectionId/$branch/$schemaHash/tables/$tableName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConnRoute: typeof ConnRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/conn': {
      id: '/conn'
      path: '/conn'
      fullPath: '/conn'
      preLoaderRoute: typeof ConnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conn/new': {
      id: '/conn/new'
      path: '/new'
      fullPath: '/conn/new'
      preLoaderRoute: typeof ConnNewRouteImport
      parentRoute: typeof ConnRoute
    }
    '/conn/$connectionId/': {
      id: '/conn/$connectionId/'
      path: '/$connectionId'
      fullPath: '/conn/$connectionId/'
      preLoaderRoute: typeof ConnConnectionIdIndexRouteImport
      parentRoute: typeof ConnRoute
    }
    '/conn/$connectionId/$branch/': {
      id: '/conn/$connectionId/$branch/'
      path: '/$connectionId/$branch'
      fullPath: '/conn/$connectionId/$branch/'
      preLoaderRoute: typeof ConnConnectionIdBranchIndexRouteImport
      parentRoute: typeof ConnRoute
    }
    '/conn/$connectionId/$branch/$schemaHash/': {
      id: '/conn/$connectionId/$branch/$schemaHash/'
      path: '/$connectionId/$branch/$schemaHash'
      fullPath: '/conn/$connectionId/$branch/$schemaHash/'
      preLoaderRoute: typeof ConnConnectionIdBranchSchemaHashIndexRouteImport
      parentRoute: typeof ConnRoute
    }
    '/conn/$connectionId/$branch/$schemaHash/tables': {
      id: '/conn/$connectionId/$branch/$schemaHash/tables'
      path: '/$connectionId/$branch/$schemaHash/tables'
      fullPath: '/conn/$connectionId/$branch/$schemaHash/tables'
      preLoaderRoute: typeof ConnConnectionIdBranchSchemaHashTablesRouteImport
      parentRoute: typeof ConnRoute
    }
    '/conn/$connectionId/$branch/$schemaHash/live-query': {
      id: '/conn/$connectionId/$branch/$schemaHash/live-query'
      path: '/$connectionId/$branch/$schemaHash/live-query'
      fullPath: '/conn/$connectionId/$branch/$schemaHash/live-query'
      preLoaderRoute: typeof ConnConnectionIdBranchSchemaHashLiveQueryRouteImport
      parentRoute: typeof ConnRoute
    }
    '/conn/$connectionId/$branch/$schemaHash/tables/': {
      id: '/conn/$connectionId/$branch/$schemaHash/tables/'
      path: '/'
      fullPath: '/conn/$connectionId/$branch/$schemaHash/tables/'
      preLoaderRoute: typeof ConnConnectionIdBranchSchemaHashTablesIndexRouteImport
      parentRoute: typeof ConnConnectionIdBranchSchemaHashTablesRoute
    }
    '/conn/$connectionId/$branch/$schemaHash/live-query/': {
      id: '/conn/$connectionId/$branch/$schemaHash/live-query/'
      path: '/'
      fullPath: '/conn/$connectionId/$branch/$schemaHash/live-query/'
      preLoaderRoute: typeof ConnConnectionIdBranchSchemaHashLiveQueryIndexRouteImport
      parentRoute: typeof ConnConnectionIdBranchSchemaHashLiveQueryRoute
    }
    '/conn/$connectionId/$branch/$schemaHash/tables/$tableName/': {
      id: '/conn/$connectionId/$branch/$schemaHash/tables/$tableName/'
      path: '/$tableName'
      fullPath: '/conn/$connectionId/$branch/$schemaHash/tables/$tableName/'
      preLoaderRoute: typeof ConnConnectionIdBranchSchemaHashTablesTableNameIndexRouteImport
      parentRoute: typeof ConnConnectionIdBranchSchemaHashTablesRoute
    }
  }
}

interface ConnConnectionIdBranchSchemaHashLiveQueryRouteChildren {
  ConnConnectionIdBranchSchemaHashLiveQueryIndexRoute: typeof ConnConnectionIdBranchSchemaHashLiveQueryIndexRoute
}

const ConnConnectionIdBranchSchemaHashLiveQueryRouteChildren: ConnConnectionIdBranchSchemaHashLiveQueryRouteChildren =
  {
    ConnConnectionIdBranchSchemaHashLiveQueryIndexRoute:
      ConnConnectionIdBranchSchemaHashLiveQueryIndexRoute,
  }

const ConnConnectionIdBranchSchemaHashLiveQueryRouteWithChildren =
  ConnConnectionIdBranchSchemaHashLiveQueryRoute._addFileChildren(
    ConnConnectionIdBranchSchemaHashLiveQueryRouteChildren,
  )

interface ConnConnectionIdBranchSchemaHashTablesRouteChildren {
  ConnConnectionIdBranchSchemaHashTablesIndexRoute: typeof ConnConnectionIdBranchSchemaHashTablesIndexRoute
  ConnConnectionIdBranchSchemaHashTablesTableNameIndexRoute: typeof ConnConnectionIdBranchSchemaHashTablesTableNameIndexRoute
}

const ConnConnectionIdBranchSchemaHashTablesRouteChildren: ConnConnectionIdBranchSchemaHashTablesRouteChildren =
  {
    ConnConnectionIdBranchSchemaHashTablesIndexRoute:
      ConnConnectionIdBranchSchemaHashTablesIndexRoute,
    ConnConnectionIdBranchSchemaHashTablesTableNameIndexRoute:
      ConnConnectionIdBranchSchemaHashTablesTableNameIndexRoute,
  }

const ConnConnectionIdBranchSchemaHashTablesRouteWithChildren =
  ConnConnectionIdBranchSchemaHashTablesRoute._addFileChildren(
    ConnConnectionIdBranchSchemaHashTablesRouteChildren,
  )

interface ConnRouteChildren {
  ConnNewRoute: typeof ConnNewRoute
  ConnConnectionIdIndexRoute: typeof ConnConnectionIdIndexRoute
  ConnConnectionIdBranchIndexRoute: typeof ConnConnectionIdBranchIndexRoute
  ConnConnectionIdBranchSchemaHashLiveQueryRoute: typeof ConnConnectionIdBranchSchemaHashLiveQueryRouteWithChildren
  ConnConnectionIdBranchSchemaHashTablesRoute: typeof ConnConnectionIdBranchSchemaHashTablesRouteWithChildren
  ConnConnectionIdBranchSchemaHashIndexRoute: typeof ConnConnectionIdBranchSchemaHashIndexRoute
}

const ConnRouteChildren: ConnRouteChildren = {
  ConnNewRoute: ConnNewRoute,
  ConnConnectionIdIndexRoute: ConnConnectionIdIndexRoute,
  ConnConnectionIdBranchIndexRoute: ConnConnectionIdBranchIndexRoute,
  ConnConnectionIdBranchSchemaHashLiveQueryRoute:
    ConnConnectionIdBranchSchemaHashLiveQueryRouteWithChildren,
  ConnConnectionIdBranchSchemaHashTablesRoute:
    ConnConnectionIdBranchSchemaHashTablesRouteWithChildren,
  ConnConnectionIdBranchSchemaHashIndexRoute:
    ConnConnectionIdBranchSchemaHashIndexRoute,
}

const ConnRouteWithChildren = ConnRoute._addFileChildren(ConnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConnRoute: ConnRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
